
$(function(){
   $(' <div class="panel panel-default">'
                        +'<div class="panel-heading" role="tab" id="headingOne">'
                        +'<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">'
                            +'<h4 class="panel-title os-titulo">'
                                    +'ordem de serviço nº= xxxx'
                                +'<span class="glyphicon glyphicon-plus" ></span>'
                            +'</h4>'
                        +'</a>'
                        +'</div>'
                        +'<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">'
                            +'<div class="panel-body">'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Solicitante</span>'
                                    +'<span class= "campo-valor">*Nome do Usuario*</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Data da Solicitação</span>'
                                    +'<span class= "campo-valor">*Data*</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Area</span>'
                                    +'<span class= "campo-valor">*area*</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Prazo</span>'
                                    +'<span class= "campo-valor">*prazo*</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Descrição</span>'
                                    +'<span class= "campo-valor">*descricao*</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Observação</span>'
                                    +'<span class= "campo-valor">*observacao*</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Status</span>'
                                    +'<span class= "campo-valor">'
                                        +'<select>'
                                           +' <option value="">----</option>'
                                            +'<option value="0">Aberto</option>'
                                            +'<option value="1">Concluido</option>'
                                            +'<option value="2">Em andamento</option>'
                                            +'<option value="3">Não sei se vai</option>'
                                        +'</select>'
                                    +'</span>'
                                +'</div>'
                                +'<div>'
                                    +'<span class= "campo-rotulo">Prioridade</span>'
                                    +'<span class= "campo-valor">'
                                        +'<select>'
                                            +'<option value =" ">---</option>'
                                            +'<option value =" 0">Urgente</option>'
                                            +'<option value =" 1">Importante</option>'
                                            +'<option value =" 2">normal</option>'
                                        +'</select>'
                                    +'</span>'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                    +'</div>').appendTo('#accordion');
    
});

